# package - issues and vulnerabilities (scan)

name: Dependency Scan 

on: 
  workflow_call:

jobs:
    dependencies-checks:
        runs-on: ubuntu-latest
        steps:
          - name: code-checkout
            uses: actions/checkout@v4

          - name: pip dependencies audit
            uses: pypa/gh-action-pip-audit@v1.1.0
            with:
        # Optional: specify a requirements file if not using a virtual environment
              requirements: requirements.txt 
        # Optional: fail the build if vulnerabilities are found
              strict: true 




