name: Deploy Flask App

on:
  workflow_run:
    workflows: ["Docker Build & Push"] # Must match the upstream workflow name EXACTLY
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    # Only deploy when the upstream Docker Build & Push workflow SUCCEEDED
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKER_TAG: ${{ github.sha}}

    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose (optional, usually pre-installed on ubuntu-latest runners)
        uses: docker/setup-compose-action@v2

      - name: deploy with docker compose
        # --pull always  → pull the latest image from Docker Hub
        # NO --build     → do NOT rebuild from Dockerfile locally
        run: docker compose down && docker compose up -d --force-recreate --pull always
